"""add contact table

Revision ID: 6439d870aee1
Revises: 46ba5c60d53d
Create Date: 2026-04-18 20:37:27.677766

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6439d870aee1"
down_revision = "46ba5c60d53d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("owner_id != contact_id", name="ck_owner_not_contact"),
        sa.ForeignKeyConstraint(["contact_id"], ["user.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["user.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("owner_id", "contact_id", name="uq_owner_contact"),
    )
    op.create_index(
        op.f("ix_contact_contact_id"), "contact", ["contact_id"], unique=False
    )
    op.create_index(op.f("ix_contact_owner_id"), "contact", ["owner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contact_owner_id"), table_name="contact")
    op.drop_index(op.f("ix_contact_contact_id"), table_name="contact")
    op.drop_table("contact")
    # ### end Alembic commands ###
