"""add username field

Revision ID: b7a5aae6ea70
Revises: 6439d870aee1
Create Date: 2026-04-18 22:52:06.314275

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b7a5aae6ea70"
down_revision = "6439d870aee1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("username", sa.String(length=255), nullable=True))
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_column("user", "username")
    # ### end Alembic commands ###
